export const QUESTION_SUCCESS = 'QUESTION_SUCCESS';
export const QUESTION_ERROR = 'QUESTION_ERROR';
export const TAG_SUCCESS = 'TAG_SUCCESS';
export const TAG_ERROR = 'TAG_ERROR';

export const QUESTIONLOADING = 'QUESTIONLOADING';
export const QUESTIONLOADED = 'QUESTIONLOADED';
export const TAGLOADING = 'TAGLOADING';
export const TAGLOADED = 'TAGLOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const GET_ERROR = 'GET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const COMBINE_SUCCESS = 'COMBINE_SUCCESS';
export const FIND_SUCCESS = 'FIND_SUCCESS';

export const QUESTION_EDITED = 'QUESTION_EDITED';
export const TAG_DELETED = 'TAG_DELETED';
export const TAG_EDITED = 'TAG_EDITED';
export const QUESTION_DELETED = 'QUESTION_DELETED';
